# Site settings
title: Kevin Klopfenstein
description: "Thoughts on technology."
baseurl: ""
url: "http://www.kevinklopfenstein.com"
githubhandle: "kklopfenstein"
twitterhandle: "klopkev"

# Build settings
markdown: kramdown
permalink: pretty
