# Site settings
title: Accidental Feature
email: kklopfenstein@gmail.com
description: "Thoughts on software engineering, programming and technology."
baseurl: ""
url: "http://kklopfenstien.github.io/"

# Build settings
markdown: kramdown
permalink: pretty
